/**
 * Shared journal context builder.
 *
 * Builds the context string injected at session start across all LLM agents
 * (pi, Claude Code, OpenCode). Contains:
 *   - Global instructions
 *   - TODO.md (if it exists)
 *   - 3 most recent journal entries (full content)
 *   - Filename listing of older entries (up to 30)
 *   - Cross-project awareness (5 recent filenames per other project)
 *
 * Used as:
 *   - Library: import { buildJournalContext } from "./index.ts"
 *   - CLI: bun config/llm/journal-context/index.ts [cwd]
 *
 * Config is read from ~/.config/llm/journal.json (generated by Nix).
 */

import { existsSync, readFileSync } from "node:fs";
import { mkdir, readdir, readFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { parseArgs } from "node:util";

/** Max recent filenames to list for the current project. */
const FILENAME_LIST_CURRENT = 30;
/** Max recent filenames to list per other project. */
const FILENAME_LIST_OTHER = 5;

export interface JournalConfig {
  notesDir: string;
  noNotesReminder: string;
  journalReminder: string;
  compactionReminder: string;
  journalSkipMessage: string;
  vanillaMessage: string;
  globalInstructions: string;
}

export interface NotesResult {
  exists: boolean;
  path: string;
  notes: Array<{ filename: string; content: string }>;
  /** All .md filenames (excluding TODO.md), most recent first. */
  allFilenames: string[];
  /** Contents of TODO.md if it exists. */
  todo: string | null;
}

export function loadJournalConfig(): JournalConfig {
  const configDir = process.env.XDG_CONFIG_HOME || join(process.env.HOME || "", ".config");
  const path = join(configDir, "llm", "journal.json");
  return JSON.parse(readFileSync(path, "utf-8")) as JournalConfig;
}

export async function getRecentNotes(notesDir: string, projectName: string): Promise<NotesResult> {
  const projectNotes = join(notesDir, projectName);

  if (!existsSync(projectNotes)) {
    await mkdir(projectNotes, { recursive: true });
    return { exists: false, path: projectNotes, notes: [], allFilenames: [], todo: null };
  }

  const files = await readdir(projectNotes);
  const mdFiles = files
    .filter((f) => f.endsWith(".md") && f !== "TODO.md")
    .sort()
    .reverse();

  const todoPath = join(projectNotes, "TODO.md");
  const todo = existsSync(todoPath) ? await readFile(todoPath, "utf-8") : null;

  if (mdFiles.length === 0) {
    return { exists: true, path: projectNotes, notes: [], allFilenames: [], todo };
  }

  const recentFiles = mdFiles.slice(0, 3);
  const notes = await Promise.all(
    recentFiles.map(async (filename) => {
      const content = await readFile(join(projectNotes, filename), "utf-8");
      return { filename, content };
    }),
  );

  return { exists: true, path: projectNotes, notes, allFilenames: mdFiles, todo };
}

async function getOtherProjectFilenames(notesDir: string, projectName: string): Promise<string[]> {
  const projectNotes = join(notesDir, projectName);
  if (!existsSync(projectNotes)) return [];

  const files = await readdir(projectNotes);
  return files
    .filter((f) => f.endsWith(".md") && f !== "TODO.md")
    .sort()
    .reverse()
    .slice(0, FILENAME_LIST_OTHER);
}

async function getOtherProjectSummaries(notesDir: string, currentProject: string): Promise<string | null> {
  if (!existsSync(notesDir)) return null;

  const dirs = await readdir(notesDir, { withFileTypes: true });
  const projects: Array<{ name: string; filenames: string[]; mostRecent: string }> = [];

  for (const dir of dirs) {
    if (!dir.isDirectory() || dir.name === currentProject) continue;
    const filenames = await getOtherProjectFilenames(notesDir, dir.name);
    if (filenames.length === 0) continue;
    projects.push({ name: dir.name, filenames, mostRecent: filenames[0] });
  }

  if (projects.length === 0) return null;

  // Sort by most recent entry (filenames are date-prefixed, descending)
  projects.sort((a, b) => b.mostRecent.localeCompare(a.mostRecent));

  const lines = projects.map((p) => {
    const names = p.filenames.map((f) => f.replace(/\.md$/, "")).join(", ");
    return `  ${p.name}: ${names}`;
  });
  return `Other project journals (recent entries):\n${lines.join("\n")}`;
}

/**
 * Structured journal context split into parts, each under the 10K char hook
 * output limit for Claude Code. Pi uses buildJournalContext() which joins them.
 */
export interface JournalParts {
  /** Global instructions + journal behavioral guidance */
  instructions: string;
  /** TODO.md + directory listing + cross-project awareness */
  metadata: string;
  /** Individual journal entries (most recent first), one per element */
  journals: string[];
}

export async function buildJournalParts(config: JournalConfig, cwd: string): Promise<JournalParts> {
  const empty: JournalParts = { instructions: "", metadata: "", journals: [] };

  if (process.env.LLM_VANILLA === "1") {
    return { ...empty, instructions: config.vanillaMessage };
  }

  let instructions = config.globalInstructions;

  if (process.env.NO_JOURNAL === "1") {
    return { ...empty, instructions: `${instructions}\n\n${config.journalSkipMessage}` };
  }

  instructions += `\n\n${config.journalReminder}`;

  const projectName = basename(cwd);
  const result = await getRecentNotes(config.notesDir, projectName);

  const metaParts: string[] = [];
  const journals: string[] = [];

  if (result.notes.length === 0) {
    let noNotes = `No previous session notes for ${projectName}.\nNotes directory: ${result.path}/\n`;
    if (!result.exists) {
      noNotes += "(Directory was just created)\n";
    }
    noNotes += `\n${config.noNotesReminder}`;
    metaParts.push(noNotes);
  } else {
    metaParts.push(`Previous session notes for ${projectName}:`);

    if (result.todo) {
      metaParts.push(`<file name="${result.path}/TODO.md">\n${result.todo}\n</file>`);
    }

    for (const note of result.notes) {
      journals.push(`<file name="${result.path}/${note.filename}">\n${note.content}\n</file>`);
    }

    if (result.allFilenames.length > 3) {
      const olderFilenames = result.allFilenames.slice(3, FILENAME_LIST_CURRENT);
      const total = result.allFilenames.length;
      let listing = olderFilenames.map((f) => f.replace(/\.md$/, "")).join("\n");
      if (total > FILENAME_LIST_CURRENT) {
        listing += `\n... and ${total - FILENAME_LIST_CURRENT} more`;
      }
      metaParts.push(
        `<directory-listing name="${result.path}" description="Older entries (${total} total, use read tool if relevant)">\n${listing}\n</directory-listing>`,
      );
    }
  }

  const otherProjects = await getOtherProjectSummaries(config.notesDir, projectName);
  if (otherProjects) {
    metaParts.push(otherProjects);
  }

  return { instructions, metadata: metaParts.join("\n\n"), journals };
}

/** Full context string (used by Pi, backward compatible). */
export async function buildJournalContext(config: JournalConfig, cwd: string): Promise<string> {
  const parts = await buildJournalParts(config, cwd);
  return [parts.instructions, parts.metadata, ...parts.journals].filter(Boolean).join("\n\n");
}

/** Resolve a named part from JournalParts. Returns empty string for missing journal indices. */
export function resolvePart(parts: JournalParts, name: string): string {
  if (name === "instructions") return parts.instructions;
  if (name === "metadata") return parts.metadata;
  if (name.startsWith("journal:")) {
    const idx = parseInt(name.split(":")[1], 10);
    return parts.journals[idx] ?? "";
  }
  return "";
}

/** CLI entry point. Exported for testing. */
export async function main(args: string[]): Promise<string> {
  const { values, positionals } = parseArgs({
    args,
    options: { part: { type: "string" } },
    allowPositionals: true,
  });
  const cwd = positionals[0] || process.cwd();
  const config = loadJournalConfig();

  if (values.part) {
    const parts = await buildJournalParts(config, cwd);
    return resolvePart(parts, values.part);
  }
  return buildJournalContext(config, cwd);
}

// CLI mode:
//   bun .../journal-context.ts [cwd]                  -- full context (Pi, legacy)
//   bun .../journal-context.ts --part <name> [cwd]    -- single part (Claude Code hooks)
//     Parts: instructions, metadata, journal:0, journal:1, journal:2
const isMainModule = typeof process !== "undefined" && process.argv[1]?.includes("journal-context");

if (isMainModule) {
  main(process.argv.slice(2)).then((output) => process.stdout.write(output));
}
