/**
 * Shared journal context builder.
 *
 * Builds the context string injected at session start across all LLM agents
 * (pi, Claude Code, OpenCode). Contains:
 *   - Global instructions
 *   - TODO.md (if it exists)
 *   - 3 most recent journal entries (full content)
 *   - Filename listing of older entries (up to 30)
 *   - Cross-project awareness (5 recent filenames per other project)
 *
 * Used as:
 *   - Library: import { buildJournalContext } from "./index.ts"
 *   - CLI: bun config/llm/journal-context/index.ts [cwd]
 *
 * Config is read from ~/.config/llm/journal.json (generated by Nix).
 */

import { existsSync, readFileSync } from "node:fs";
import { mkdir, readdir, readFile } from "node:fs/promises";
import { basename, join } from "node:path";

/** Max recent filenames to list for the current project. */
const FILENAME_LIST_CURRENT = 30;
/** Max recent filenames to list per other project. */
const FILENAME_LIST_OTHER = 5;

export interface JournalConfig {
  notesDir: string;
  noNotesReminder: string;
  journalReminder: string;
  compactionReminder: string;
  journalSkipMessage: string;
  vanillaMessage: string;
  globalInstructions: string;
}

export interface NotesResult {
  exists: boolean;
  path: string;
  notes: Array<{ filename: string; content: string }>;
  /** All .md filenames (excluding TODO.md), most recent first. */
  allFilenames: string[];
  /** Contents of TODO.md if it exists. */
  todo: string | null;
}

export function loadJournalConfig(): JournalConfig {
  const configDir = process.env.XDG_CONFIG_HOME || join(process.env.HOME || "", ".config");
  const path = join(configDir, "llm", "journal.json");
  return JSON.parse(readFileSync(path, "utf-8")) as JournalConfig;
}

export async function getRecentNotes(notesDir: string, projectName: string): Promise<NotesResult> {
  const projectNotes = join(notesDir, projectName);

  if (!existsSync(projectNotes)) {
    await mkdir(projectNotes, { recursive: true });
    return { exists: false, path: projectNotes, notes: [], allFilenames: [], todo: null };
  }

  const files = await readdir(projectNotes);
  const mdFiles = files
    .filter((f) => f.endsWith(".md") && f !== "TODO.md")
    .sort()
    .reverse();

  const todoPath = join(projectNotes, "TODO.md");
  const todo = existsSync(todoPath) ? await readFile(todoPath, "utf-8") : null;

  if (mdFiles.length === 0) {
    return { exists: true, path: projectNotes, notes: [], allFilenames: [], todo };
  }

  const recentFiles = mdFiles.slice(0, 3);
  const notes = await Promise.all(
    recentFiles.map(async (filename) => {
      const content = await readFile(join(projectNotes, filename), "utf-8");
      return { filename, content };
    }),
  );

  return { exists: true, path: projectNotes, notes, allFilenames: mdFiles, todo };
}

async function getOtherProjectFilenames(notesDir: string, projectName: string): Promise<string[]> {
  const projectNotes = join(notesDir, projectName);
  if (!existsSync(projectNotes)) return [];

  const files = await readdir(projectNotes);
  return files
    .filter((f) => f.endsWith(".md") && f !== "TODO.md")
    .sort()
    .reverse()
    .slice(0, FILENAME_LIST_OTHER);
}

async function getOtherProjectSummaries(notesDir: string, currentProject: string): Promise<string | null> {
  if (!existsSync(notesDir)) return null;

  const dirs = await readdir(notesDir, { withFileTypes: true });
  const projects: Array<{ name: string; filenames: string[]; mostRecent: string }> = [];

  for (const dir of dirs) {
    if (!dir.isDirectory() || dir.name === currentProject) continue;
    const filenames = await getOtherProjectFilenames(notesDir, dir.name);
    if (filenames.length === 0) continue;
    projects.push({ name: dir.name, filenames, mostRecent: filenames[0] });
  }

  if (projects.length === 0) return null;

  // Sort by most recent entry (filenames are date-prefixed, descending)
  projects.sort((a, b) => b.mostRecent.localeCompare(a.mostRecent));

  const lines = projects.map((p) => {
    const names = p.filenames.map((f) => f.replace(/\.md$/, "")).join(", ");
    return `  ${p.name}: ${names}`;
  });
  return `Other project journals (recent entries):\n${lines.join("\n")}`;
}

export async function buildJournalContext(config: JournalConfig, cwd: string): Promise<string> {
  if (process.env.LLM_VANILLA === "1") {
    return config.vanillaMessage;
  }

  let context = `${config.globalInstructions}\n\n`;

  if (process.env.NO_JOURNAL === "1") {
    return `${context}${config.journalSkipMessage}`;
  }

  const projectName = basename(cwd);
  const result = await getRecentNotes(config.notesDir, projectName);

  if (result.notes.length === 0) {
    context += `No previous session notes for ${projectName}.\n`;
    context += `Notes directory: ${result.path}/\n`;
    if (!result.exists) {
      context += "(Directory was just created)\n";
    }
    context += `\n${config.noNotesReminder}\n${config.journalReminder}`;
  } else {
    context += `Previous session notes for ${projectName}:\n\n`;

    if (result.todo) {
      context += `<file name="${projectName}/TODO.md">\n${result.todo}\n</file>\n\n`;
    }

    for (const note of result.notes) {
      context += `<file name="${projectName}/${note.filename}">\n${note.content}\n</file>\n\n`;
    }

    if (result.allFilenames.length > 3) {
      const olderFilenames = result.allFilenames.slice(3, FILENAME_LIST_CURRENT);
      const total = result.allFilenames.length;
      let listing = olderFilenames.map((f) => f.replace(/\.md$/, "")).join("\n");
      if (total > FILENAME_LIST_CURRENT) {
        listing += `\n... and ${total - FILENAME_LIST_CURRENT} more`;
      }
      context += `<directory-listing name="${result.path}" description="Older entries (${total} total, use read tool if relevant)">\n${listing}\n</directory-listing>\n\n`;
    }

    context += config.journalReminder;
  }

  const otherProjects = await getOtherProjectSummaries(config.notesDir, projectName);
  if (otherProjects) {
    context += `\n\n${otherProjects}`;
  }

  return context;
}

// CLI mode: bun .../journal-context.ts [cwd]
const isMainModule = typeof process !== "undefined" && process.argv[1]?.includes("journal-context");

if (isMainModule) {
  const cwd = process.argv[2] || process.cwd();
  const config = loadJournalConfig();
  buildJournalContext(config, cwd).then((ctx) => {
    process.stdout.write(ctx);
  });
}
