/**
 * Journal config reader.
 *
 * Reads ~/.config/llm/journal.json generated by Nix (modules/home-manager/llm.nix).
 * Replaces the old __PLACEHOLDER__ template substitution pattern.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

export interface JournalConfig {
  notesDir: string;
  noNotesReminder: string;
  journalReminder: string;
  compactionReminder: string;
  journalSkipMessage: string;
  vanillaMessage: string;
  globalInstructions: string;
}

let cached: JournalConfig | null = null;

export function loadJournalConfig(): JournalConfig {
  if (cached) return cached;

  const configDir = process.env.XDG_CONFIG_HOME || join(process.env.HOME || "", ".config");
  const path = join(configDir, "llm", "journal.json");
  cached = JSON.parse(readFileSync(path, "utf-8")) as JournalConfig;
  return cached;
}
