/**
 * Pi journal extension.
 *
 * Injects global instructions and journal notes at session start,
 * reminds to journal before compaction, and supports env var overrides:
 *   LLM_VANILLA=1 - skip all custom context
 *   NO_JOURNAL=1  - skip journal reading (fresh session)
 *
 * Config is read from ~/.config/llm/journal.json (generated by Nix).
 */

import { existsSync } from "node:fs";
import { mkdir, readdir, readFile } from "node:fs/promises";
import { basename, join } from "node:path";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { loadJournalConfig } from "./config.js";

interface NotesResult {
  exists: boolean;
  path: string;
  notes: Array<{ filename: string; content: string }>;
}

async function getRecentNotes(notesDir: string, projectName: string): Promise<NotesResult> {
  const projectNotes = join(notesDir, projectName);

  if (!existsSync(projectNotes)) {
    await mkdir(projectNotes, { recursive: true });
    return { exists: false, path: projectNotes, notes: [] };
  }

  const files = await readdir(projectNotes);
  const mdFiles = files
    .filter((f) => f.endsWith(".md"))
    .sort()
    .reverse()
    .slice(0, 3);

  if (mdFiles.length === 0) {
    return { exists: true, path: projectNotes, notes: [] };
  }

  const notes = await Promise.all(
    mdFiles.map(async (filename) => {
      const content = await readFile(join(projectNotes, filename), "utf-8");
      return { filename, content };
    }),
  );

  return { exists: true, path: projectNotes, notes };
}

function buildContext(config: ReturnType<typeof loadJournalConfig>, result: NotesResult, projectName: string): string {
  let context = `${config.globalInstructions}\n\n`;

  if (result.notes.length === 0) {
    context += `No previous session notes for ${projectName}.\n`;
    context += `Notes directory: ${result.path}/\n`;
    if (!result.exists) {
      context += "(Directory was just created)\n";
    }
    context += `\n${config.noNotesReminder}\n${config.journalReminder}`;
  } else {
    context += `Previous session notes for ${projectName}:\n\n`;
    for (const note of result.notes) {
      context += `--- ${note.filename} ---\n${note.content}\n\n`;
    }
    context += config.journalReminder;
  }

  return context;
}

export default function journalExtension(pi: ExtensionAPI) {
  const config = loadJournalConfig();
  let cachedContext = "";
  let firstPrompt = true;

  async function loadContext(cwd: string) {
    if (process.env.LLM_VANILLA === "1") {
      cachedContext = config.vanillaMessage;
      return;
    }

    if (process.env.NO_JOURNAL === "1") {
      cachedContext = `${config.globalInstructions}\n\n${config.journalSkipMessage}`;
      return;
    }

    const projectName = basename(cwd);
    const result = await getRecentNotes(config.notesDir, projectName);
    cachedContext = buildContext(config, result, projectName);

    pi.events.emit("journal:loaded", { projectName, notes: result.notes });
  }

  pi.on("session_start", async (_event, ctx) => {
    firstPrompt = true;
    await loadContext(ctx.cwd);
  });

  pi.on("session_switch", async (_event, ctx) => {
    firstPrompt = true;
    await loadContext(ctx.cwd);
  });

  pi.on("before_agent_start", async () => {
    if (!firstPrompt || !cachedContext) return;
    firstPrompt = false;

    return {
      message: {
        customType: "journal-context",
        content: cachedContext,
        display: false,
      },
    };
  });

  pi.on("session_before_compact", async (_event, ctx) => {
    if (process.env.LLM_VANILLA === "1") return;
    ctx.ui.notify("Context compacting - journal your progress!", "warning");
    return undefined;
  });
}
