# Generated by nixos-generate-config from running UTM VM.
# Filesystems use mkDefault so disk-image.nix can override during image builds.
{
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # Boot
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "virtio_pci"
    "usbhid"
  ];
  # Filesystems -- mkDefault so disk-image.nix can override during image builds
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-uuid/f222513b-ded1-49fa-b591-20ce86a2fe7f";
    fsType = "ext4";
  };
  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ]; # root-only access -- ESP contains random seed
  };

  # Disk image size (default is 1 GB, too small for GNOME + KDE + dev tools)
  virtualisation.diskSize = 32 * 1024; # 32 GB

  # VM resources
  hardware.graphics.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
