/**
 * Vision extension — route image reads to a vision-capable sidecar model.
 *
 * When the main model doesn't support image input (input: ["text"] only),
 * this extension intercepts image content from the `read` tool's results
 * and replaces it with a text description generated by the `vision` sidecar role.
 *
 * Also registers a `describe_image` tool the main model can call explicitly
 * for targeted image analysis (OCR, layout, etc.).
 *
 * When the main model supports images natively, the extension is a no-op.
 *
 * Configuration: `vision` role in ~/.pi/agent/roles.json
 *   { "vision": { "models": [{ "ref": "zai/glm-4.6v-flash", "thinking": "off" }] } }
 */

import { existsSync, readFileSync } from "node:fs";
import { extname } from "node:path";
import type { ImageContent, TextContent } from "@mariozechner/pi-ai";
import {
  type ExtensionAPI,
  type ExtensionContext,
  isReadToolResult,
  type ModelRegistry,
} from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { extractText, hasRole, reloadConfig, type SidecarResult, sidecarComplete } from "../shared/model-roles.js";

// ── Constants ──

const IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg", ".ico", ".tiff", ".tif"]);

const VISION_SYSTEM_PROMPT = `You are a vision assistant. Describe the provided image accurately and concisely.
Follow the user's instructions for what to focus on. If no specific instructions, provide:
- A clear description of what's visible
- Any text content (OCR) if present
- Layout/structure if it's a UI screenshot or diagram
Be factual. Don't guess at content you can't see clearly.`;

// ── Helpers ──

function isImageFile(filePath: string): boolean {
  const ext = extname(filePath).toLowerCase();
  return IMAGE_EXTENSIONS.has(ext);
}

function modelSupportsVision(ctx: ExtensionContext): boolean {
  return ctx.model?.input?.includes("image") ?? false;
}

function hasImageContent(content: (TextContent | ImageContent)[]): boolean {
  return content.some((c) => c.type === "image");
}

function extractImageParts(content: (TextContent | ImageContent)[]): ImageContent[] {
  return content.filter((c): c is ImageContent => c.type === "image");
}

// ── Vision sidecar call ──

async function describeImage(
  image: ImageContent,
  prompt: string,
  modelRegistry: ModelRegistry,
  signal?: AbortSignal,
): Promise<string | null> {
  if (!hasRole("vision")) {
    return null;
  }

  const context = {
    systemPrompt: VISION_SYSTEM_PROMPT,
    messages: [
      {
        role: "user" as const,
        content: [
          { type: "image" as const, data: image.data, mimeType: image.mimeType },
          { type: "text" as const, text: prompt },
        ],
        timestamp: Date.now(),
      },
    ],
  };

  const result: SidecarResult | null = await sidecarComplete("vision", context, modelRegistry, { signal });
  if (!result) return null;

  return extractText(result.message);
}

// ── Extension ──

export default function visionExtension(pi: ExtensionAPI) {
  // Track whether the current model needs vision assistance
  let needsVisionAssist = false;

  function updateVisionState(ctx: ExtensionContext) {
    reloadConfig();
    needsVisionAssist = !modelSupportsVision(ctx) && hasRole("vision");

    if (needsVisionAssist) {
      ctx.ui.setStatus("vision", ctx.ui.theme.fg("muted", "eye:on"));
    } else {
      ctx.ui.setStatus("vision", undefined);
    }
  }

  // Re-evaluate on session start and model change
  pi.on("session_start", (_event, ctx) => {
    updateVisionState(ctx);
  });

  pi.on("model_select", (_event, ctx) => {
    updateVisionState(ctx);
  });

  // ── Intercept read tool results with images ──

  pi.on("tool_result", async (event, ctx) => {
    if (!needsVisionAssist) return;
    if (!isReadToolResult(event)) return;

    // Check if this read returned image content
    if (!hasImageContent(event.content)) return;

    const filePath = (event.input as { path?: string }).path ?? "";
    if (!isImageFile(filePath)) return;

    const images = extractImageParts(event.content);
    if (images.length === 0) return;

    // Describe each image and replace with text
    const descriptions: string[] = [];
    for (let i = 0; i < images.length; i++) {
      const img = images[i];
      const label = images.length === 1 ? "this image" : `image ${i + 1}`;
      const description = await describeImage(
        img,
        `Describe ${label} in detail. Include any visible text.`,
        ctx.modelRegistry,
        ctx.signal,
      );
      if (description) {
        descriptions.push(`[Vision: ${label}]\n${description}`);
      } else {
        descriptions.push(`[Vision: ${label} — vision model unavailable, cannot describe]`);
      }
    }

    // Replace image content with text descriptions
    const textContent: TextContent[] = descriptions.map((text) => ({
      type: "text" as const,
      text,
    }));

    return { content: textContent };
  });

  // ── Explicit describe_image tool ──

  pi.registerTool({
    name: "describe_image",
    label: "Describe Image",
    description: [
      "Analyze an image file using a vision model. Returns a text description of the image content.",
      "Use this when you need to understand what's in a screenshot, diagram, photo, or any image file.",
      "Specify what to focus on: OCR text, layout, colors, UI elements, etc.",
      "Note: The current model cannot see images directly — this tool uses a vision-capable model.",
    ].join(" "),
    parameters: Type.Object({
      path: Type.String({ description: "Path to the image file" }),
      prompt: Type.Optional(
        Type.String({
          description:
            "What to focus on in the analysis. E.g. 'Extract all text (OCR)', 'Describe the UI layout', 'What does this diagram show?'",
        }),
      ),
    }),

    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      if (!needsVisionAssist) {
        // Model supports vision natively — shouldn't need this tool
        return {
          content: [
            {
              type: "text",
              text: "The current model supports image input natively. Use the `read` tool to view the image directly.",
            },
          ],
          details: {},
        };
      }

      const filePath = params.path;
      if (!existsSync(filePath)) {
        return {
          content: [{ type: "text", text: `File not found: ${filePath}` }],
          details: {},
          isError: true,
        };
      }

      if (!isImageFile(filePath)) {
        return {
          content: [
            {
              type: "text",
              text: `Not an image file: ${filePath} (${extname(filePath)}). Supported: ${[...IMAGE_EXTENSIONS].join(", ")}`,
            },
          ],
          details: {},
          isError: true,
        };
      }

      // Read and base64-encode the image
      const data = readFileSync(filePath);
      const base64 = data.toString("base64");

      // Determine MIME type from extension
      const ext = extname(filePath).toLowerCase();
      const mimeMap: Record<string, string> = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".gif": "image/gif",
        ".webp": "image/webp",
        ".bmp": "image/bmp",
        ".svg": "image/svg+xml",
        ".ico": "image/x-icon",
        ".tiff": "image/tiff",
        ".tif": "image/tiff",
      };
      const mimeType = mimeMap[ext] ?? "application/octet-stream";

      const image: ImageContent = { type: "image", data: base64, mimeType };
      const prompt = params.prompt ?? "Describe this image in detail. Include any visible text.";

      const description = await describeImage(image, prompt, ctx.modelRegistry, ctx.signal);

      if (!description) {
        return {
          content: [
            {
              type: "text",
              text: "Vision model unavailable. Configure the 'vision' role in roles.json with a vision-capable model.",
            },
          ],
          details: {},
          isError: true,
        };
      }

      return {
        content: [{ type: "text", text: description }],
        details: {},
      };
    },
  });
}
